---
  - name: 2.1.1 Ensure chargen services are not enabled (Scored)
    shell: grep -R "^chargen" /etc/inetd.*
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - name: 2.1.2 Ensure daytime services are not enabled (Scored)
    shell: grep -R "^daytime" /etc/inetd.*
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - name: 2.1.3 Ensure discard services are not enabled (Scored)
    shell: grep -R "^discard" /etc/inetd.*
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - name: 2.1.4 Ensure echo services are not enabled (Scored)
    shell: grep -R "^echo" /etc/inetd.*
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - name: 2.1.5 Ensure time services are not enabled (Scored)
    shell: grep -R "^time" /etc/inetd.*
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - name: 2.1.6 Ensure rsh services are not enabled (Scored)
    shell: grep -R "^shell" /etc/inetd.*;grep -R "^login" /etc/inetd.*;grep -R "^exec" /etc/inetd.*
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - name: 2.1.7 Ensure talk services are not enabled (Scored)
    shell: grep -R "^talk" /etc/inetd.*;grep -R "^ntalk" /etc/inetd.*
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - name: 2.1.8 Ensure telnet services are not enabled (Scored)
    shell: grep -R "^telnet" /etc/inetd.*
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - name: 2.1.9 Ensure tftp services are not enabled (Scored)
    shell: grep -R "^tftp" /etc/inetd.*
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - name: 2.1.10 Ensure xinetd services are not enabled (Scored)
    shell: ls /etc/rc*.d | grep xinetd
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig xinetd off;systemctl disable xinetd;update-rc.d xinetd disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  # - name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
  #   shell: rpm -q chrony;rpm -q ntp || dpkg -s ntp;dpkg -s chrony
  #   register: out
  #   failed_when: >
  #     "ntp is not installed" in out.stdout or "chrony is not installed" in out.stdout
  #   ignore_errors: true
  #   changed_when: false

  # - shell: |
  #      yum install ntp -y;apt-get install ntp -y;zypper install ntp -y
  #   ignore_errors: true
  #   when: out is failed and remediation == 'YES'

  - name: 2.2.1.2 Ensure ntp is configured (Scored)
    shell: grep -E "^(server|pool)" /etc/ntp.conf
    register: out
    failed_when: >
      "server" not in out.stdout 
    ignore_errors: true
    changed_when: false

  - template:
      src: templates/ntp.conf.j2
      dest: /etc/ntp.conf
      mode: 0644
      owner: root
      group: root
      backup: true
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - shell: systemctl restart ntpd
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.1.3 Ensure chrony is configured (Scored)
    shell: grep -E "^(server|pool)" /etc/chrony.conf
    register: out
    failed_when: >
      "server" not in out.stdout 
    ignore_errors: true
    changed_when: false

  - name: 2.2.1.4 Ensure systemd-timesyncd is configured (Scored)
    shell: timedatectl status
    register: out
    failed_when: >
      out.stdout | length == 0
    ignore_errors: true
    changed_when: false

  - name: 2.2.2 Ensure X Window System is not installed (Scored)
    shell: rpm -qa xorg-x11* || dpkg -l xserver-xorg*
    register: out
    failed_when: >
      out.stdout | length != 0 and "no packages found" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
       yum remove xorg-x11* -y;apt-get remove xserver-xorg* -y;zypper remove xorg-x11* -y
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.3 Ensure Avahi Server is not enabled (Scored)
    shell: ls /etc/rc*.d | grep avahi-daemon
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig avahi-daemon off;systemctl disable avahi-daemon;update-rc.d avahi-daemon disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.4 Ensure CUPS is not enabled (Scored)
    shell: ls /etc/rc*.d | grep cups
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig cups off;systemctl disable cups;update-rc.d cups disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.5 Ensure DHCP Server is not enabled (Scored)
    shell: ls /etc/rc*.d | grep dhcpd
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig dhcpd off;systemctl disable dhcpd;update-rc.d dhcpd disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.6 Ensure LDAP Server is not enabled (Scored)
    shell: ls /etc/rc*.d | grep sldap
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig sldap off;systemctl disable sldap;update-rc.d sldap disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.7 Ensure NFS and RPC are not enabled (Scored)
    shell: ls /etc/rc*.d | grep rpcbind
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig rpcbind off;systemctl disable rpcbind;update-rc.d rpcbind disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.8 Ensure DNS Server is not enabled (Scored)
    shell: ls /etc/rc*.d | grep named
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig named off;systemctl disable named;update-rc.d named disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.9 Ensure FTP Server is not enabled (Scored)
    shell: ls /etc/rc*.d | grep vsftpd
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig vsftpd off;systemctl disable vsftpd;update-rc.d vsftpd disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.10 Ensure HTTP server is not enabled (Scored)
    shell: ls /etc/rc*.d | grep httpd
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig httpd off;systemctl disable httpd;update-rc.d httpd disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.11 Ensure IMAP and POP3 server is not enabled (Scored)
    shell: ls /etc/rc*.d | grep dovecot
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig dovecot off;systemctl disable dovecot;update-rc.d dovecot disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.12 Ensure Samba is not enabled (Scored)
    shell: ls /etc/rc*.d | grep smb
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig smb off;systemctl disable smb;update-rc.d smb disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.13 Ensure HTTP Proxy Server is not enabled (Scored)
    shell: ls /etc/rc*.d | grep squid
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig squid off;systemctl disable squid;update-rc.d squid disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.14 Ensure SNMP Server is not enabled (Scored)
    shell: ls /etc/rc*.d | grep snmpd
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig snmpd off;systemctl disable snmpd;update-rc.d snmpd disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.15 Ensure mail transfer agent is configured for local-only mode (Scored)
    shell: ss -lntu | grep -E ':25\s' | grep -E -v '\s(127.0.0.1|::1):25\s'
    register: out
    failed_when: >
      out.stdout | length != 0 
    ignore_errors: true
    changed_when: false

  - name: 2.2.16 Ensure rsync service is not enabled (Scored)
    shell: ls /etc/rc*.d | grep rsyncd
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig rsyncd off;systemctl disable rsyncd;update-rc.d rsyncd disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.2.17 Ensure NIS Server is not enabled (Scored)
    shell: ls /etc/rc*.d | grep ypserv
    register: out
    failed_when: >
      out.stdout | length != 0 and "No such file or directory" not in out.stderr
    ignore_errors: true
    changed_when: false

  - shell: |
        chkconfig ypserv off;systemctl disable ypserv;update-rc.d ypserv disable
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.3.1 Ensure NIS Client is not installed (Scored)
    shell: rpm -q ypbind || dpkg -s ypbind
    register: prompt
    failed_when: >
      "not installed" not in prompt.stdout
    ignore_errors: true
    changed_when: false

  - shell: |
       yum remove ypbind -y;apt-get remove ypbind -y;zypper remove ypbind -y
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.3.2 Ensure rsh client is not installed (Scored)
    shell: rpm -q rsh || dpkg -s rsh
    register: prompt
    failed_when: >
      "not installed" not in prompt.stdout
    ignore_errors: true
    changed_when: false

  - shell: |
       yum remove rsh -y;apt-get remove rsh -y;zypper remove rsh -y
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.3.3 Ensure talk client is not installed (Scored)
    shell: rpm -q talk || dpkg -s talk
    register: prompt
    failed_when: >
      "not installed" not in prompt.stdout
    ignore_errors: true
    changed_when: false

  - shell: |
       yum remove talk -y;apt-get remove talk -y;zypper remove talk -y
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.3.4 Ensure telnet client is not installed (Scored)
    shell: rpm -q telnet || dpkg -s telnet
    register: prompt
    failed_when: >
      "not installed" not in prompt.stdout
    ignore_errors: true
    changed_when: false

  - shell: |
       yum remove telnet -y;apt-get remove telnet -y;zypper remove telnet -y
    ignore_errors: true
    when: out is failed and remediation == 'YES'

  - name: 2.3.5 Ensure LDAP client is not installed (Scored)
    shell: rpm -q openldap-clients || dpkg -s openldap-clients
    register: prompt
    failed_when: >
      "not installed" not in prompt.stdout
    ignore_errors: true
    changed_when: false

  - shell: |
       yum remove openldap-clients -y;apt-get remove openldap-clients -y;zypper remove openldap-clients -y
    ignore_errors: true
    when: out is failed and remediation == 'YES'


